version: "3.1"

services:
  mongo_db:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db

  server:
    image: nodejs
    build: .
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      MONGODB_URL: mongodb://mongo_db:27017/TestIntergration
      PORT: 5000
    depends_on:
      - mongo_db
  
  mongoo_seed:
    build: ./mongo-seed

    links:
      - mongo_db

volumes:
  mongo-data:
