name: Backend CI/CD

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Permet d'exécuter le workflow manuellement

jobs:
  build_test_and_deploy:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
      fail-fast: false # Empêche un échec d'étape d'annuler tout le job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter (si applicable)
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        run: npm test -- --config=jest.config.js
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project to Vercel (Only on main branch)
        if: github.ref == 'refs/heads/main'
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Notify Frontend Workflow (Trigger Frontend Deployment)
      #   if: success()
      #   run: |
      #     curl -X POST -H "Accept: application/vnd.github.v3+json" \
      #          -H "Authorization: token ${{ secrets.PERSONNAL_ACCESS_TOKEN }}" \
      #          --data '{"event_type": "deploy_backend"}' \
      #          https://api.github.com/repos/Yoan01/ci-cd-ynov/dispatches
